In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

Now Importing my dataset

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/credit_scoring_synthetic_dataset (1).csv")
df.head()

,age,monthly_income,existing_debt,loan_amount,credit_history_years,missed_payments_12m,late_payments_30d,late_payments_90d,employment_years,dependents,credit_utilization,defaulted
0,25,148987,109923,789672,2.6,0,0,0,11.2,5,0.345,0
1,59,65275,102206,383227,21.9,2,0,1,1.5,2,0.260,0
2,53,91596,218587,650321,2.2,1,0,0,4.1,3,0.191,0
3,42,19926,31771,38023,5.8,2,1,0,4.4,0,0.454,0
4,42,39706,41356,62401,14.3,0,0,1,6.0,0,0.071,0

In [ ]:
df.shape

(1200, 12)

In [ ]:
df.isnull().sum()

age                     0
monthly_income          0
existing_debt           0
loan_amount             0
credit_history_years    0
missed_payments_12m     0
late_payments_30d       0
late_payments_90d       0
employment_years        0
dependents              0
credit_utilization      0
defaulted               0
dtype: int64

In [ ]:
df.head()

,age,monthly_income,existing_debt,loan_amount,credit_history_years,missed_payments_12m,late_payments_30d,late_payments_90d,employment_years,dependents,credit_utilization,defaulted
0,25,148987,109923,789672,2.6,0,0,0,11.2,5,0.345,0
1,59,65275,102206,383227,21.9,2,0,1,1.5,2,0.260,0
2,53,91596,218587,650321,2.2,1,0,0,4.1,3,0.191,0
3,42,19926,31771,38023,5.8,2,1,0,4.4,0,0.454,0
4,42,39706,41356,62401,14.3,0,0,1,6.0,0,0.071,0

In [ ]:
X=df[["age","monthly_income","existing_debt","loan_amount","credit_history_years","missed_payments_12m","late_payments_30d","late_payments_90d","employment_years","dependents","credit_utilization"]]
y=df["defaulted"]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
model=LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
precision = precision_score(y_test, y_pred)
print("Precision Score:", precision)

Precision Score: 0.5853658536585366

In [ ]:
recall = recall_score(y_test, y_pred)
print("Recall Score:", recall)

Recall Score: 0.25806451612903225

In [ ]:
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.3582089552238806

In [ ]:
roc_auc = roc_auc_score(y_test, y_pred)
print("ROC-AUC Score:", roc_auc)

ROC-AUC Score: 0.5712091288128155

DecisionTree Model

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = model.predict(X_test)
precision = precision_score(y_test, y_pred)
print("Precision Score:", precision)

Precision Score: 0.40217391304347827

In [ ]:
recall = recall_score(y_test, y_pred)
print("Recall Score:", recall)

Recall Score: 0.3978494623655914

In [ ]:
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.4

In [ ]:
roc_auc = roc_auc_score(y_test, y_pred)
print("ROC-AUC Score:", roc_auc)

ROC-AUC Score: 0.511849901250823